export const buttonsVertical = [
    {
        title: 'AC',
        onPressText: 'AC',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '',
        onPressText: '',
        disable: true,
        big: 'big50',
        bgc: '#646464',
    },
    {
        title: '÷',
        onPressText: '/',
        disable: false,
        big: false,
        bgc: '#f0a03b',
    },
    {
        title: '7',
        onPressText: '7',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '8',
        onPressText: '8',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '9',
        onPressText: '9',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '×',
        onPressText: '*',
        disable: false,
        big: false,
        bgc: '#f0a03b',
    },
    {
        title: '4',
        onPressText: '4',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '5',
        onPressText: '5',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '6',
        onPressText: '6',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '-',
        onPressText: '-',
        disable: false,
        big: false,
        bgc: '#f0a03b',
    },
    {
        title: '1',
        onPressText: '1',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '2',
        onPressText: '2',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '3',
        onPressText: '3',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '+',
        onPressText: '+',
        disable: false,
        big: false,
        bgc: '#f0a03b',
    },
    {
        title: '0',
        onPressText: '0',
        disable: false,
        big: 'big50',
        bgc: '#7c7d7d',
    },
    {
        title: '.',
        onPressText: '.',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '=',
        onPressText: '=',
        disable: false,
        big: false,
        bgc: '#f0a03b',
    },
];

////////////////////////////////
export const buttonsHorizontal = [
    {
        title: '(',
        onPressText: '(',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: ')',
        onPressText: ')',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'mc',
        onPressText: 'mc',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'm+',
        onPressText: 'm+',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'm-',
        onPressText: 'm-',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'mr',
        onPressText: 'mr',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'AC',
        onPressText: 'AC',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '+/-',
        onPressText: '+/-',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '%',
        onPressText: '%',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '÷',
        onPressText: '/',
        disable: false,
        big: false,
        bgc: '#f0a03b',
    },
    {
        title: '2ⁿᵈ',
        onPressText: '2nd',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'x²',
        onPressText: 'x2',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'x³',
        onPressText: 'x3',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'xʸ',
        onPressText: 'xy',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'eˣ',
        onPressText: 'ex',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '10ˣ',
        onPressText: '10x',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '7',
        onPressText: '7',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '8',
        onPressText: '8',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '9',
        onPressText: '9',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '×',
        onPressText: '*',
        disable: false,
        big: false,
        bgc: '#f0a03b',
    },
    {
        title: '⅟ₓ',
        onPressText: '1/x',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '²√x',
        onPressText: '2sqrtx',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '³√x',
        onPressText: '3sqrtx',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'ʸ√x',
        onPressText: 'ysqrtx',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'ln',
        onPressText: 'ln',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'log₁₀',
        onPressText: 'log10',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '4',
        onPressText: '4',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '5',
        onPressText: '5',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '6',
        onPressText: '6',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '-',
        onPressText: '-',
        disable: false,
        big: false,
        bgc: '#f0a03b',
    },
    {
        title: 'x!',
        onPressText: 'x!',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'sin',
        onPressText: 'sin',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'cos',
        onPressText: 'cos',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'tan',
        onPressText: 'tan',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'e',
        onPressText: 'e',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'EE',
        onPressText: 'EE',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '1',
        onPressText: '1',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '2',
        onPressText: '2',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '3',
        onPressText: '3',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '+',
        onPressText: '+',
        disable: false,
        big: false,
        bgc: '#f0a03b',
    },
    {
        title: 'Rad',
        onPressText: 'Rad',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'sinh',
        onPressText: 'sinh',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'cosh',
        onPressText: 'cosh',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'tanh',
        onPressText: 'tanh',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'π',
        onPressText: 'pi',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: 'Rand',
        onPressText: 'Rand',
        disable: false,
        big: false,
        bgc: '#646464',
    },
    {
        title: '0',
        onPressText: '0',
        disable: false,
        big: 'big20',
        bgc: '#7c7d7d',
    },
    {
        title: '.',
        onPressText: '.',
        disable: false,
        big: false,
        bgc: '#7c7d7d',
    },
    {
        title: '=',
        onPressText: '=',
        disable: false,
        big: false,
        bgc: '#f0a03b',
    },
];
